version: "3.9"
services:
  db:
    image: postgres
    container_name: banco_postegres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postegres_crud_bussola
      POSTGRES_DB: kanban
      POSTGRES_PASSWORD: 12345
